k3s_version: v1.34.2+k3s1
k3s_channel: stable
k3s_agent_extra_args: ""
k3s_controller_extra_args: ""
k3s_admin_user: alejandro
k3s_cluster_token: ""  # Add your token here
node_packages:
  - curl
  - iptables
  - nfs-common
  - ca-certificates
timezone: UTC
