all:
  vars:
    ansible_user: alejandro
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    controller:
      hosts:
        cnat:
          ansible_host: cnat.local
          k3s_api_ip: 172.19.181.254
    nodes:
      vars:
        ansible_ssh_common_args: >-
          -o ProxyJump=alejandro@cnat.local
        k3s_server_url: https://172.19.181.254:6443
      hosts:
        p1:
          ansible_host: p1
          ansible_user: radxa
        p2:
          ansible_host: p2
          ansible_user: radxa
