k3s_install_script_url: https://get.k3s.io
k3s_server_config_path: /etc/rancher/k3s/config.yaml
k3s_data_dir: /var/lib/rancher/k3s
k3s_api_ip: 172.19.181.254
k3s_server_tls_sans: []
k3s_controller_extra_args: ""
